import party

settlements_translation = {
    "אבו ג'ווייעד (שבט)": "Abu Juwei'eid (tribe)",
    "אבו גוש": "Abu Ghosh",
    "אבו סנאן": "Abu Snan",
    "אבו עבדון (שבט)": "Abu Abdun (tribe)",
    "אבו קורינאת (שבט)": "Abu Qureinat (tribe)",
    "אבו קרינאת (יישוב)": "Abu Qrenat (locality)",
    "אבו רובייעה (שבט)": "Abu Rubaiya (tribe)",
    "אבו רוקייק (שבט)": "Abu Rukeiq (tribe)",
    "אבו תלול": "Abu Talul",
    "אבטין": "Ibtin",
    "אבטליון": "Avtalion",
    "אביאל": "Aviel",
    "אביבים": "Avivim",
    "אביגדור": "Avigdor",
    "אביחיל": "Avihayil",
    "אביטל": "Avital",
    "אביעזר": "Aviezer",
    "אבירים": "Abbirim",
    "אבן יהודה": "Even Yehuda",
    "אבן מנחם": "Even Menachem",
    "אבן ספיר": "Even Sapir",
    "אבן שמואל": "Even Shmuel",
    "אבני איתן": "Avnei Eitan",
    "אבני חפץ": "Avnei Hefetz",
    "אבשלום": "Avshalom",
    "אדורה": "Adora",
    "אדירים": "Adirim",
    "אדמית": "Adamit",
    "אדרת": "Aderet",
    "אודים": "Udim",
    "אודם": "Odem",
    "אוהד": "Ohad",
    "אום אל-פחם": "Umm al-Fahm",
    "אום אל-קוטוף": "Umm al-Qutuf",
    "אום בטין": "Umm Batin",
    "אומן": "Oman",
    "אומץ": "Ometz",
    "אופקים": "Ofakim",
    "אור הגנוז": "Or HaGanuz",
    "אור הנר": "Or HaNer",
    "אור יהודה": "Or Yehuda",
    "אור עקיבא": "Or Akiva",
    "אורה": "Ora",
    "אורות": "Orot",
    "אורטל": "Ortal",
    "אורים": "Urim",
    "אורנית": "Oranit",
    "אושה": "Usha",
    "אזור": "Azor",
    "אחווה": "Ahawa",
    "אחוזם": "Ahuzam",
    "אחוזת ברק": "Ahuzat Barak",
    "אחיהוד": "Ahihud",
    "אחיטוב": "Ahituv",
    "אחיסמך": "Ahisamakh",
    "אחיעזר": "Ahiezer",
    "אטרש (שבט)": "Atrash (tribe)",
    "איבים": "Ibim",
    "אייל": "Eyal",
    "איילת השחר": "Ayelet HaShahar",
    "אילון": "Elon",
    "אילות": "Eilot",
    "אילניה": "Ilaniya",
    "אילת": "Eilat",
    "אירוס": "Irus",
    "איתמר": "Itamar",
    "איתן": "Eitan",
    "אכסאל": "Iksal",
    "אל סייד": "Al-Sayyid",
    "אל-עריאן": "Al-Arian",
    "אל-רום": "El-Rom",
    "אלומה": "Aluma",
    "אלומות": "Alumot",
    "אלון הגליל": "Alon HaGalil",
    "אלון מורה": "Alon Moreh",
    "אלון שבות": "Alon Shvut",
    "אלוני אבא": "Alonei Abba",
    "אלוני הבשן": "Alonei HaBashan",
    "אלוני יצחק": "Alonei Yitzhak",
    "אלונים": "Alonim",
    "אלי-עד": "Eliad",
    "אליאב": "Eli'av",
    "אליכין": "Elyakhin",
    "אליפז": "Elifaz",
    "אליפלט": "Elifelet",
    "אליקים": "Elyakim",
    "אלישיב": "Elyashiv",
    "אלישמע": "Elishama",
    "אלמגור": "Almagor",
    "אלמוג": "Almog",
    "אלעד": "El'ad",
    "אלעזר": "Elazar",
    "אלפי מנשה": "Alfei Menashe",
    "אלקוש": "Elkosh",
    "אלקנה": "Elkana",
    "אמונים": "Emunim",
    "אמירים": "Amirim",
    "אמנון": "Amnon",
    "אמציה": "Amatzia",
    "אניעם": "Aniam",
    "אסד (שבט)": "Assad (tribe)",
    "אספר": "Esper",
    "אעבלין": "I'billin",
    "אעצם (שבט)": "A'sam (tribe)",
    "אפיק": "Afik",
    "אפיקים": "Afikim",
    "אפק": "Afek",
    "אפרת": "Efrat",
    "ארבל": "Arbel",
    "ארגמן": "Argaman",
    "ארז": "Erez",
    "אריאל": "Ariel",
    "ארסוף": "Arsuf",
    "אשבול": "Eshbol",
    "אשדוד": "Ashdod",
    "אשדות יעקב  (איחוד)": "Ashdod Ya'akov (Ichud)",
    "אשדות יעקב  (מאוחד)": "Ashdod Ya'akov (Meuchad)",
    "אשחר": "Eshtaul",
    "אשכולות": "Eshkolot",
    "אשל הנשיא": "Eshel HaNasi",
    "אשלים": "Ashalim",
    "אשקלון": "Ashkelon",
    "אשרת": "Asherat",
    "אשתאול": "Eshtaol",
    "באקה אל-גרביה": "Baqa al-Gharbiyye",
    "באר אורה": "Be'er Ora",
    "באר גנים": "Be'er Ganim",
    "באר טוביה": "Be'er Tuvia",
    "באר יעקב": "Be'er Ya'akov",
    "באר שבע": "Be'er Sheva",
    "בארות יצחק": "Be'erot Yitzhak",
    "בארותיים": "Be'erotayim",
    "בארי": "Be'eri",
    "בוסתן הגליל": "Bustan HaGalil",
    "בועיינה-נוג'ידאת": "Bu'eine Nujeidat",
    "בוקעאתא": "Buq'ata",
    "בורגתה": "Burgata",
    "בחן": "Bahan",
    "בטחה": "Bitkha",
    "ביצרון": "Bitzaron",
    "ביר אל-מכסור": "Bir al-Maksur",
    "ביר הדאג'": "Bir Hadaj",
    "ביריה": "Birya",
    "בית אורן": "Beit Oren",
    "בית אל": "Bet El",
    "בית אלעזרי": "Beit El'azari",
    "בית אלפא": "Beit Alpha",
    "בית אריה": "Beit Aryeh",
    "בית ג'ן": "Beit Jann",
    "בית גוברין": "Beit Guvrin",
    "בית גמליאל": "Beit Gamliel",
    "בית דגן": "Beit Dagan",
    "בית הגדי": "Beit HaGedi",
    "בית הלוי": "Beit HaLevi",
    "בית הלל": "Beit Hillel",
    "בית העמק": "Beit HaEmek",
    "בית הערבה": "Beit HaArava",
    "בית השיטה": "Beit HaShita",
    "בית זיד": "Beit Zaid",
    "בית זית": "Beit Zayit",
    "בית זרע": "Beit Zera",
    "בית חורון": "Beit Horon",
    "בית חירות": "Beit Herut",
    "בית חלקיה": "Beit Hilkiya",
    "בית חנן": "Beit Hanan",
    "בית חנניה": "Beit Hanania",
    "בית חשמונאי": "Beit Hashmonai",
    "בית יהושע": "Beit Yehoshua",
    "בית יוסף": "Beit Yosef",
    "בית ינאי": "Beit Yanai",
    "בית יצחק-שער חפר": "Beit Yitzhak-Sha'ar Hefer",
    "בית לחם הגלילית": "Bethlehem of Galilee",
    "בית מאיר": "Beit Meir",
    "בית נחמיה": "Beit Nehemia",
    "בית ניר": "Beit Nir",
    "בית נקופה": "Beit Nekofa",
    "בית עובד": "Beit Oved",
    "בית עוזיאל": "Beit Uziel",
    "בית עזרא": "Beit Ezra",
    "בית עריף": "Beit Arif",
    "בית צבי": "Beit Zvi",
    "בית קמה": "Beit Kama",
    "בית קשת": "Beit Keshet",
    "בית רבן": "Beit Raban",
    "בית רימון": "Beit Rimon",
    "בית שאן": "Beit She'an",
    "בית שמש": "Beit Shemesh",
    "בית שערים": "Beit She'arim",
    "בית שקמה": "Beit Shikma",
    "ביתן אהרן": "Bitan Aharon",
    "ביתר עילית": "Beitar Illit",
    "בלפוריה": "Balfouria",
    "בן זכאי": "Ben Zakai",
    "בן עמי": "Ben Ami",
    "בן שמן (כפר נוער)": "Ben Shemen (Youth Village)",
    "בן שמן (מושב)": "Ben Shemen (Moshav)",
    "בני ברק": "Bnei Brak",
    "בני דקלים": "Bnei Dkalim",
    "בני דרום": "Bnei Darom",
    "בני דרור": "Bnei Dror",
    "בני יהודה": "Bnei Yehuda",
    "בני נצרים": "Bnei Netzarim",
    "בני עטרות": "Bnei Atarot",
    "בני עי\"ש": "Bnei Ayish",
    "בני ציון": "Bnei Zion",
    "בני ראם": "Bnei Re'em",
    "בניה": "Bneiaya",
    "בנימינה-גבעת עדה": "Binyamina-Giv'at Ada",
    "בסמ\"ה": "Basma",
    "בסמת טבעון": "Basmat Tab'un",
    "בענה": "Bi'ina",
    "בצרה": "Batzra",
    "בצת": "Betzet",
    "בקוע": "Beko'a",
    "בקעות": "Beka'ot",
    "בר גיורא": "Bar Giora",
    "בר יוחאי": "Bar Yochai",
    "ברוכין": "Brukhin",
    "ברור חיל": "Bror Hayil",
    "ברוש": "Brosh",
    "ברכה": "Bracha",
    "ברכיה": "Barkhia",
    "ברעם": "Bar'am",
    "ברק": "Barak",
    "ברקאי": "Barkai",
    "ברקן": "Barkan",
    "ברקת": "Bareket",
    "בת הדר": "Bat Hadar",
    "בת חן": "Bat Chen",
    "בת חפר": "Bat Hefer",
    "בת ים": "Bat Yam",
    "בת עין": "Bat Ayin",
    "בת שלמה": "Bat Shlomo",
    "ג'דיידה-מכר": "Jadeidi-Makr",
    "ג'ולס": "Julis",
    "ג'לג'וליה": "Jaljulia",
    "ג'נאביב (שבט)": "Janabib (tribe)",
    "ג'סר א-זרקא": "Jisr az-Zarqa",
    "ג'ש (גוש חלב)": "Jish (Gush Halav)",
    "ג'ת": "Jatt",
    "גאולי תימן": "Ge'ulei Teman",
    "גאולים": "Geulim",
    "גאליה": "Ge'alia",
    "גבולות": "Gvulot",
    "גבים": "Gevim",
    "גבע": "Geva",
    "גבע בנימין": "Geva Binyamin",
    "גבע כרמל": "Geva Carmel",
    "גבעולים": "Givolim",
    "גבעון החדשה": "Giv'on HaHadasha",
    "גבעות בר": "Giv'at Bar",
    "גבעת אבני": "Giv'at Avni",
    "גבעת אלה": "Giv'at Ela",
    "גבעת ברנר": "Giv'at Brenner",
    "גבעת השלושה": "Giv'at HaShlosha",
    "גבעת זאב": "Giv'at Ze'ev",
    "גבעת ח\"ן": "Giv'at Hen",
    "גבעת חיים (איחוד)": "Giv'at Haim (Ichud)",
    "גבעת חיים (מאוחד)": "Giv'at Haim (Meuchad)",
    "גבעת יואב": "Giv'at Yo'av",
    "גבעת יערים": "Giv'at Ye'arim",
    "גבעת ישעיהו": "Giv'at Yeshayahu",
    "גבעת כ\"ח": "Giv'at Ko'ah",
    "גבעת ניל\"י": "Giv'at Nili",
    "גבעת עוז": "Giv'at Oz",
    "גבעת שמואל": "Giv'at Shmuel",
    "גבעת שפירא": "Giv'at Shapira",
    "גבעתי": "Giv'ati",
    "גבעתיים": "Giv'atayim",
    "גברעם": "Gvar'am",
    "גבת": "Gvat",
    "גדות": "Gadot",
    "גדיש": "Gadish",
    "גדעונה": "Gidona",
    "גדרה": "Gedera",
    "גונן": "Gonen",
    "גורן": "Goren",
    "גורנות הגליל": "Gornot HaGalil",
    "גזית": "Gazit",
    "גזר": "Gezer",
    "גיאה": "Ga'ah",
    "גיבתון": "Givton",
    "גיזו": "Gizo",
    "גילון": "Gilon",
    "גילת": "Gilat",
    "גינוסר": "Ginosar",
    "גיניגר": "Ginegar",
    "גינתון": "Ginton",
    "גיתה": "Gita",
    "גיתית": "Gtit",
    "גלאון": "Gla'on",
    "גלגל": "Gilgal",
    "גליל ים": "Galil Yam",
    "גלעד (אבן יצחק)": "Gil'ad (Even Yitzhak)",
    "גמזו": "Gimzo",
    "גן הדרום": "Gan HaDarom",
    "גן השומרון": "Gan HaShomron",
    "גן חיים": "Gan Haim",
    "גן יאשיה": "Gan Yoshiyya",
    "גן יבנה": "Gan Yavne",
    "גן נר": "Gan Ner",
    "גן שורק": "Gan Sorek",
    "גן שלמה": "Gan Shlomo",
    "גן שמואל": "Gan Shmuel",
    "גנות": "Ganot",
    "גנות הדר": "Ganot Hadar",
    "גני הדר": "Ganei Hadar",
    "גני טל": "Ganei Tal",
    "גני יוחנן": "Ganei Yehohanan",
    "גני מודיעין": "Ganei Modi'in",
    "גני עם": "Ganei Am",
    "גני תקווה": "Ganei Tikva",
    "געש": "Ga'ash",
    "געתון": "Ga'ton",
    "גפן": "Gefen",
    "גרופית": "Grufit",
    "גשור": "Gesher",
    "גשר": "Gesher",
    "גשר הזיו": "Gesher HaZiv",
    "גת (קיבוץ)": "Gat (kibbutz)",
    "גת רימון": "Gat Rimon",
    "דאלית אל-כרמל": "Daliyat al-Carmel",
    "דבורה": "Devora",
    "דבוריה": "Daburiya",
    "דבירה": "Devira",
    "דברת": "Dvrat",
    "דגניה א'": "Degania Alef",
    "דגניה ב'": "Degania Bet",
    "דוב\"ב": "Dovev",
    "דולב": "Dolev",
    "דור": "Dor",
    "דורות": "Dorot",
    "דחי": "Dahi",
    "דייר אל-אסד": "Deir al-Asad",
    "דייר חנא": "Deir Hanna",
    "דימונה": "Dimona",
    "דישון": "Dishon",
    "דליה": "Dalia",
    "דלתון": "Dalton",
    "דמיידה": "Dmeide",
    "דן": "Dan",
    "דפנה": "Dafna",
    "דקל": "Dekel",
    "דריג'את": "Draijat",
    "האון": "HaOn",
    "הבונים": "HaBonim",
    "הגושרים": "HaGoshrim",
    "הדר עם": "Hadar Am",
    "הוד השרון": "Hod HaSharon",
    "הודיה": "Hodiya",
    "הוואשלה (שבט)": "Hawashla (tribe)",
    "הוזייל (שבט)": "Huzayel (tribe)",
    "הושעיה": "Hoshaya",
    "הזורע": "HaZore'a",
    "הזורעים": "HaZor'im",
    "החותרים": "HaHotrim",
    "היוגב": "HaYogev",
    "הילה": "Hila",
    "המעפיל": "HaMa'apil",
    "הסוללים": "HaSollelim",
    "העוגן": "HaOgen",
    "הר אדר": "Har Adar",
    "הר גילה": "Har Gillo",
    "הר עמשא": "Har Amasa",
    "הראל": "Harel",
    "הרדוף": "Harduf",
    "הרצליה": "Herzliya",
    "הררית": "Hararit",
    "ורד יריחו": "Vered Yericho",
    "ורדון": "Vardon",
    "זבדיאל": "Zavdiel",
    "זוהר": "Zohar",
    "זיקים": "Zikim",
    "זיתן": "Zetan",
    "זכרון יעקב": "Zichron Ya'akov",
    "זכריה": "Zecharya",
    "זמר": "Zemer",
    "זמרת": "Zimrat",
    "זנוח": "Zanoah",
    "זרועה": "Zru'a",
    "זרזיר": "Zarzir",
    "זרחיה": "Zrahya",
    "ח'ואלד": "Khawaled",
    "חבצלת השרון": "Havatzelet HaSharon",
    "חבר": "Hever",
    "חברון": "Hebron",
    "חגור": "Hagor",
    "חגי": "Hagai",
    "חגלה": "Hagla",
    "חד-נס": "Had-Nes",
    "חדיד": "Hadid",
    "חדרה": "Hadera",
    "חולדה": "Hulda",
    "חולון": "Holon",
    "חולית": "Holit",
    "חולתה": "Hulata",
    "חוסן": "Hosen",
    "חוסנייה": "Husniya",
    "חופית": "Hofit",
    "חוקוק": "Hukok",
    "חורה": "Hura",
    "חורפיש": "Hurfeish",
    "חורשים": "Horshim",
    "חזון": "Hazon",
    "חיבת ציון": "Hibat Zion",
    "חיננית": "Hinanit",
    "חיפה": "Haifa",
    "חירות": "Herut",
    "חלוץ": "Halutz",
    "חלץ": "Heletz",
    "חמאם": "Hamam",
    "חמד": "Hemed",
    "חמדיה": "Hamadia",
    "חמדת": "Hemdat",
    "חמרה": "Hamra",
    "חניאל": "Hanniel",
    "חניתה": "Hanita",
    "חנתון": "Hanaton",
    "חספין": "Haspin",
    "חפץ חיים": "Hafetz Haim",
    "חפצי-בה": "Hafetz Hayim",
    "חצב": "Hatzeva",
    "חצבה": "Hatzeva",
    "חצור הגלילית": "Hatzor HaGlilit",
    "חצור-אשדוד": "Hatzor-Ashdod",
    "חצרים": "Hatzerim",
    "חרב לאת": "Herev Le'et",
    "חרוצים": "Harutzim",
    "חריש": "Harish",
    "חרמש": "Hermesh",
    "חרשים": "Harashim",
    "חשמונאים": "Hashmonaim",
    "טבריה": "Tiberias",
    "טובא-זנגריה": "Tuba-Zangariyye",
    "טורעאן": "Tur'an",
    "טייבה": "Tayibe",
    "טייבה (בעמק)": "Tayibe (in the valley)",
    "טירה": "Tira",
    "טירת יהודה": "Tirat Yehuda",
    "טירת כרמל": "Tirat Carmel",
    "טירת צבי": "Tirat Zvi",
    "טל שחר": "Tal Shahar",
    "טל-אל": "Tal-El",
    "טללים": "Telalim",
    "טלמון": "Talmon",
    "טמרה": "Tamra",
    "טמרה (יזרעאל)": "Tamra (Jezreel)",
    "טנא": "Tene",
    "טפחות": "Tefahot",
    "יאנוח-ג'ת": "Yanuh-Jat",
    "יבול": "Yevul",
    "יבנאל": "Yavne'el",
    "יבנה": "Yavne",
    "יגור": "Yagur",
    "יגל": "Yagel",
    "יד בנימין": "Yad Binyamin",
    "יד השמונה": "Yad HaShmona",
    "יד חנה": "Yad Hana",
    "יד מרדכי": "Yad Mordechai",
    "יד נתן": "Yad Natan",
    "יד רמב\"ם": "Yad Rambam",
    "יהוד-מונוסון": "Yehud-Monoson",
    "יהל": "Yahel",
    "יובל": "Yuval",
    "יובלים": "Yovelim",
    "יודפת": "Yodfat",
    "יונתן": "Yonatan",
    "יושיביה": "Yoshivya",
    "יזרעאל": "Jezreel",
    "יחיעם": "Yechi'am",
    "יטבתה": "Yotvata",
    "ייט\"ב": "Yitav",
    "יכיני": "Yakhini",
    "ינוב": "Yanuv",
    "ינון": "Yinon",
    "יסוד המעלה": "Yesud HaMa'ala",
    "יסודות": "Yesodot",
    "יסעור": "Yas'ur",
    "יעד": "Ya'ad",
    "יעף": "Ya'af",
    "יערה": "Ya'ara",
    "יפיע": "Yafia",
    "יפית": "Yafit",
    "יפעת": "Yif'at",
    "יפתח": "Yiftach",
    "יצהר": "Itzhar",
    "יציץ": "Yatzitz",
    "יקום": "Yakum",
    "יקיר": "Yakir",
    "יקנעם (מושבה)": "Yokneam (Moshava)",
    "יקנעם עילית": "Yokneam Illit",
    "יראון": "Yar'on",
    "ירדנה": "Yardena",
    "ירוחם": "Yeruham",
    "ירושלים": "Jerusalem",
    "ירחיב": "Yarchiv",
    "ירכא": "Yarka",
    "ירקונה": "Yarkona",
    "ישע": "Yesha",
    "ישעי": "Yish'i",
    "ישרש": "Yashresh",
    "יתד": "Yated",
    "כאבול": "Kabul",
    "כאוכב אבו אל-היג'א": "Kaokab Abu al-Hija",
    "כברי": "Kabri",
    "כדיתה": "Kedita",
    "כוכב השחר": "Kochav HaShahar",
    "כוכב יאיר": "Kochav Yair",
    "כוכב יעקב": "Kochav Ya'akov",
    "כוכב מיכאל": "Kochav Michael",
    "כורזים": "Korazim",
    "כחל": "Kachal",
    "כחלה": "Kahlah",
    "כיסופים": "Kissufim",
    "כישור": "Kishor",
    "כליל": "Klil",
    "כלנית": "Kalanit",
    "כמאנה": "Kamana",
    "כמהין": "Kmehin",
    "כמון": "Kamon",
    "כנף": "Kanaf",
    "כנרת (מושבה)": "Kinneret (Moshava)",
    "כנרת (קבוצה)": "Kinneret (Group)",
    "כסיפה": "Kuseife",
    "כסלון": "Kesalon",
    "כסרא-סמיע": "Kisra-Sumei",
    "כעביה-טבאש-חג'אג'רה": "Ka'abiyye-Tabbash-Hajajre",
    "כפר אביב": "Kfar Aviv",
    "כפר אדומים": "Kfar Adumim",
    "כפר אוריה": "Kfar Uriah",
    "כפר אחים": "Kfar Ahim",
    "כפר ביאליק": "Kfar Bialik",
    "כפר ביל\"ו": "Kfar Bilu",
    "כפר בלום": "Kfar Blum",
    "כפר בן נון": "Kfar Ben Nun",
    "כפר ברא": "Kfar Bara",
    "כפר ברוך": "Kfar Baruch",
    "כפר גדעון": "Kfar Gideon",
    "כפר גלים": "Kfar Galim",
    "כפר גליקסון": "Kfar Glickson",
    "כפר גלעדי": "Kfar Giladi",
    "כפר דניאל": "Kfar Daniel",
    "כפר האורנים": "Kfar HaOranim",
    "כפר החורש": "Kfar HaHoresh",
    "כפר המכבי": "Kfar HaMaccabi",
    "כפר הנגיד": "Kfar HaNagid",
    "כפר הנשיא": "Kfar HaNasi",
    "כפר הס": "Kfar HaS",
    "כפר הרא\"ה": "Kfar HaRoeh",
    "כפר הרי\"ף": "Kfar Harif",
    "כפר ויתקין": "Kfar Vitkin",
    "כפר ורבורג": "Kfar Warburg",
    "כפר ורדים": "Kfar Vradim",
    "כפר זיתים": "Kfar Zeitim",
    "כפר חב\"ד": "Kfar Chabad",
    "כפר חושן": "Kfar Hoshen",
    "כפר חיטים": "Kfar Hitim",
    "כפר חיים": "Kfar Haim",
    "כפר חנניה": "Kfar Hanania",
    "כפר חסידים א'": "Kfar Hasidim Alef",
    "כפר חסידים ב'": "Kfar Hasidim Bet",
    "כפר חרוב": "Kfar Haruv",
    "כפר טרומן": "Kfar Truman",
    "כפר יאסיף": "Kfar Yassif",
    "כפר ידידיה": "Kfar Yedidia",
    "כפר יהושע": "Kfar Yehoshua",
    "כפר יונה": "Kfar Yona",
    "כפר יחזקאל": "Kfar Yehezkel",
    "כפר יעבץ": "Kfar Ya'bez",
    "כפר כמא": "Kfar Kama",
    "כפר כנא": "Kfar Kanna",
    "כפר מונש": "Kfar Monash",
    "כפר מימון": "Kfar Maimon",
    "כפר מל\"ל": "Kfar Malal",
    "כפר מנדא": "Kfar Manda",
    "כפר מנחם": "Kfar Menahem",
    "כפר מסריק": "Kfar Masaryk",
    "כפר מצר": "Kfar Metz'er",
    "כפר מרדכי": "Kfar Mordechai",
    "כפר נטר": "Kfar Netter",
    "כפר סאלד": "Kfar Szold",
    "כפר סבא": "Kfar Saba",
    "כפר סילבר": "Kfar Silver",
    "כפר סירקין": "Kfar Sirkin",
    "כפר עזה": "Kfar Azza",
    "כפר עציון": "Kfar Etzion",
    "כפר פינס": "Kfar Pines",
    "כפר קאסם": "Kfar Qasem",
    "כפר קיש": "Kfar Kish",
    "כפר קרע": "Kfar Qara",
    "כפר ראש הנקרה": "Kfar Rosh HaNikra",
    "כפר רוזנואלד (זרעית)": "Kfar Rosenwald (Zarit)",
    "כפר רופין": "Kfar Ruppin",
    "כפר רות": "Kfar Rut",
    "כפר שמאי": "Kfar Shammai",
    "כפר שמואל": "Kfar Shmuel",
    "כפר שמריהו": "Kfar Shemaryahu",
    "כפר תבור": "Kfar Tavor",
    "כפר תפוח": "Kfar Tapuach",
    "כרכום": "Karkom",
    "כרם בן זמרה": "Kerem Ben Zimra",
    "כרם יבנה (ישיבה)": "Kerem Yavne (Yeshiva)",
    "כרם מהר\"ל": "Kerem Maharal",
    "כרם שלום": "Kerem Shalom",
    "כרמי יוסף": "Karmei Yosef",
    "כרמי צור": "Karmei Tzur",
    "כרמי קטיף": "Karmei Katif",
    "כרמיאל": "Karmiel",
    "כרמיה": "Karmia",
    "כרמים": "Kramim",
    "כרמל": "Carmel",
    "לבון": "Lavon",
    "לביא": "Lavi",
    "לבנים": "Livnim",
    "להב": "Lahav",
    "להבות הבשן": "Lahavot HaBashan",
    "להבות חביבה": "Lahavot Haviva",
    "להבים": "Lehavim",
    "לוד": "Lod",
    "לוזית": "Luzit",
    "לוחמי הגיטאות": "Lochamei HaGeta'ot",
    "לוטם": "Lotem",
    "לוטן": "Lotan",
    "לימן": "Liman",
    "לכיש": "Lakhish",
    "לפיד": "Lapid",
    "לפידות": "Lapidot",
    "לקיה": "Lakiya",
    "מאור": "Ma'or",
    "מאיר שפיה": "Meir Shefeya",
    "מבוא ביתר": "Mevo Beitar",
    "מבוא דותן": "Mevo Dotan",
    "מבוא חורון": "Mevo Horon",
    "מבוא חמה": "Mevo Hama",
    "מבוא מודיעים": "Mevo Modi'im",
    "מבועים": "Mabu'im",
    "מבטחים": "Mivtahim",
    "מבקיעים": "Mavki'im",
    "מבשרת ציון": "Mevaseret Zion",
    "מג'ד אל-כרום": "Majd al-Kurum",
    "מג'דל שמס": "Majdal Shams",
    "מגאר": "Maghar",
    "מגדים": "Megadim",
    "מגדל": "Migdal",
    "מגדל העמק": "Migdal HaEmek",
    "מגדל עוז": "Migdal Oz",
    "מגדלים": "Migdalim",
    "מגידו": "Megiddo",
    "מגל": "Magal",
    "מגן": "Magen",
    "מגן שאול": "Magen Sha'ul",
    "מגשימים": "Magshimim",
    "מדרך עוז": "Midrach Oz",
    "מדרשת בן גוריון": "Midreshet Ben Gurion",
    "מודיעין עילית": "Modi'in Illit",
    "מודיעין-מכבים-רעות": "Modi'in-Maccabim-Re'ut",
    "מולדת": "Moledet",
    "מוצא עילית": "Motza Illit",
    "מוקייבלה": "Mukheiba",
    "מורן": "Moran",
    "מורשת": "Moreshet",
    "מזור": "Mazor",
    "מזכרת בתיה": "Mazkeret Batya",
    "מזרע": "Mizra",
    "מזרעה": "Mazra'a",
    "מחולה": "Mehola",
    "מחנה הילה": "Camp Hila",
    "מחנה טלי": "Camp Tali",
    "מחנה יהודית": "Camp Yehudit",
    "מחנה יוכבד": "Camp Yokheved",
    "מחנה יפה": "Camp Yafe",
    "מחנה מרים": "Camp Miriam",
    "מחנה תל נוף": "Camp Tel Nof",
    "מחניים": "Mahanayim",
    "מחסיה": "Mahseya",
    "מטולה": "Metula",
    "מטע": "Matta",
    "מי עמי": "Mei Ami",
    "מיטב": "Meitav",
    "מייסר": "Meiser",
    "מיצר": "Metzar",
    "מירב": "Merav",
    "מירון": "Meron",
    "מישר": "Meishar",
    "מיתר": "Meitar",
    "מכורה": "Mekhora",
    "מכחול": "Makchul",
    "מכמורת": "Mikhmoret",
    "מכמנים": "Mikhmanim",
    "מלאה": "Mle'a",
    "מלילות": "Melilot",
    "מלכיה": "Malkiya",
    "מנוחה": "Menucha",
    "מנוף": "Manof",
    "מנות": "Manot",
    "מנחמיה": "Menahemia",
    "מנרה": "Manara",
    "מנשית זבדה": "Manshiyat Zabda",
    "מסד": "Massad",
    "מסדה": "Masada",
    "מסילות": "Mesillot",
    "מסילת ציון": "Mesillat Zion",
    "מסלול": "Maslul",
    "מסעדה": "Mas'ade",
    "מסעודין אל-עזאזמה": "Mas'udiyye al-'Azazme",
    "מעברות": "Ma'abarot",
    "מעגלים": "Ma'agalim",
    "מעגן": "Ma'agan",
    "מעגן מיכאל": "Ma'agan Michael",
    "מעוז חיים": "Maoz Haim",
    "מעון": "Ma'on",
    "מעונה": "Ma'ona",
    "מעטפות חיצוניות": "Outer envelopes",
    "מעיליא": "Mi'ilya",
    "מעין ברוך": "Ma'ayan Barukh",
    "מעין צבי": "Ma'ayan Zvi",
    "מעלה אדומים": "Ma'ale Adumim",
    "מעלה אפרים": "Ma'ale Efrayim",
    "מעלה גלבוע": "Ma'ale Gilboa",
    "מעלה גמלא": "Ma'ale Gamla",
    "מעלה החמישה": "Ma'ale HaHamisha",
    "מעלה לבונה": "Ma'ale Levona",
    "מעלה מכמש": "Ma'ale Mikhmas",
    "מעלה עירון": "Ma'ale Iron",
    "מעלה עמוס": "Ma'ale Amos",
    "מעלה שומרון": "Ma'ale Shomron",
    "מעלות-תרשיחא": "Ma'alot-Tarshiha",
    "מענית": "Ma'anit",
    "מעש": "Ma'as",
    "מפלסים": "Mefalsim",
    "מצדות יהודה": "Metzadot Yehuda",
    "מצובה": "Metzuba",
    "מצליח": "Matzliach",
    "מצפה": "Mitzpe",
    "מצפה אבי\"ב": "Mitzpe Aviv",
    "מצפה אילן": "Mitzpe Ilan",
    "מצפה יריחו": "Mitzpe Yericho",
    "מצפה נטופה": "Mitzpe Netofa",
    "מצפה רמון": "Mitzpe Ramon",
    "מצפה שלם": "Mitzpe Shalem",
    "מצר": "Metzer",
    "מקווה ישראל": "Mikve Israel",
    "מרגליות": "Margaliot",
    "מרום גולן": "Merom Golan",
    "מרחב עם": "Merhav Am",
    "מרחביה (מושב)": "Merhavya (Moshav)",
    "מרחביה (קיבוץ)": "Merhavya (Kibbutz)",
    "מרכז שפירא": "Merkaz Shapira",
    "משאבי שדה": "Mash'abbe Sade",
    "משגב דב": "Misgav Dov",
    "משגב עם": "Misgav Am",
    "משהד": "Mashhad",
    "משואה": "Masua",
    "משואות יצחק": "Masu'ot Yitzhak",
    "משכיות": "Maskiot",
    "משמר איילון": "Mishmar Ayalon",
    "משמר דוד": "Mishmar David",
    "משמר הירדן": "Mishmar HaYarden",
    "משמר הנגב": "Mishmar HaNegev",
    "משמר העמק": "Mishmar HaEmek",
    "משמר השבעה": "Mishmar HaShiv'a",
    "משמר השרון": "Mishmar HaSharon",
    "משמרות": "Mishmarot",
    "משמרת": "Mishmeret",
    "משען": "Mish'an",
    "מתן": "Matan",
    "מתת": "Matat",
    "מתתיהו": "Matityahu",
    "נאות גולן": "Ne'ot Golan",
    "נאות הכיכר": "Ne'ot HaKikar",
    "נאות מרדכי": "Ne'ot Mordechai",
    "נאות סמדר": "Ne'ot Smadar",
    "נאעורה": "Na'ura",
    "נבטים": "Nevatim",
    "נגבה": "Negba",
    "נגוהות": "Negohot",
    "נהורה": "Nehora",
    "נהלל": "Nahalal",
    "נהריה": "Nahariya",
    "נוב": "Nov",
    "נוגה": "Noga",
    "נוה צוף": "Neve Tzof",
    "נווה": "Neve",
    "נווה אור": "Neve Ur",
    "נווה אטי\"ב": "Neve Ativ",
    "נווה אילן": "Neve Ilan",
    "נווה איתן": "Neve Eitan",
    "נווה דניאל": "Neve Daniel",
    "נווה זוהר": "Neve Zohar",
    "נווה זיו": "Neve Ziv",
    "נווה ים": "Neve Yam",
    "נווה ימין": "Neve Yamin",
    "נווה ירק": "Neve Yarak",
    "נווה מבטח": "Neve Mivtah",
    "נווה מיכאל": "Neve Michael",
    "נווה שלום": "Neve Shalom",
    "נועם": "No'am",
    "נוף איילון": "Nof Ayalon",
    "נוף הגליל": "Nof HaGalil",
    "נופים": "Nofim",
    "נופית": "Nofit",
    "נופך": "Nofech",
    "נוקדים": "Nokdim",
    "נורדיה": "Nordia",
    "נורית": "Nurit",
    "נחושה": "Nehusha",
    "נחל עוז": "Nahal Oz",
    "נחלה": "Nahala",
    "נחליאל": "Nahli'el",
    "נחלים": "Nechalim",
    "נחם": "Naham",
    "נחף": "Nehaf",
    "נחשולים": "Nahsholim",
    "נחשון": "Nahshon",
    "נחשונים": "Nahshonim",
    "נטועה": "Netu'a",
    "נטור": "Natur",
    "נטע": "Neta",
    "נטעים": "Neta'im",
    "נטף": "Nataf",
    "ניין": "Nilin",
    "ניל\"י": "Nili",
    "ניצן": "Nitzan",
    "ניצן ב'": "Nitzan Bet",
    "ניצנה (קהילת חינוך)": "Nitzana (Educational Community)",
    "ניצני סיני": "Nitzanei Sinai",
    "ניצני עוז": "Nitzanei Oz",
    "ניצנים": "Nitzanim",
    "ניר אליהו": "Nir Eliyahu",
    "ניר בנים": "Nir Banim",
    "ניר גלים": "Nir Galim",
    "ניר דוד (תל עמל)": "Nir David (Tel Amal)",
    "ניר ח\"ן": "Nir Hen",
    "ניר יפה": "Nir Yafe",
    "ניר יצחק": "Nir Yitzhak",
    "ניר ישראל": "Nir Israel",
    "ניר משה": "Nir Moshe",
    "ניר עוז": "Nir Oz",
    "ניר עם": "Nir Am",
    "ניר עציון": "Nir Etzion",
    "ניר עקיבא": "Nir Akiva",
    "ניר צבי": "Nir Zvi",
    "נירים": "Nirim",
    "נירית": "Nirit",
    "נס הרים": "Nes Harim",
    "נס עמים": "Nes Ammim",
    "נס ציונה": "Ness Ziona",
    "נעורים": "Ne'urim",
    "נעלה": "Na'ale",
    "נעמ\"ה": "Na'ama",
    "נען": "Na'an",
    "נצאצרה (שבט)": "Natsatsera (tribe)",
    "נצר חזני": "Netzer Hazani",
    "נצר סרני": "Netzer Sereni",
    "נצרת": "Nazareth",
    "נשר": "Nesher",
    "נתיב הגדוד": "Netiv HaGdud",
    "נתיב הל\"ה": "Netiv HaLamed-Heh",
    "נתיב העשרה": "Netiv HaAsara",
    "נתיב השיירה": "Netiv HaShayara",
    "נתיבות": "Netivot",
    "נתניה": "Netanya",
    "סאג'ור": "Sajur",
    "סאסא": "Sasa",
    "סביון": "Savyon",
    "סגולה": "Segula",
    "סואעד (חמרייה)": "Suweid (Hamriyye)",
    "סולם": "Sulam",
    "סוסיה": "Susya",
    "סופה": "Sufa",
    "סח'נין": "Sakhnin",
    "סייד (שבט)": "Sayyid (tribe)",
    "סלמה": "Salama",
    "סלעית": "Sal'it",
    "סמר": "Samar",
    "סנסנה": "Sansana",
    "סעד": "Sa'ad",
    "סעוה": "Sa'wa",
    "סער": "Sa'ar",
    "ספיר": "Sapir",
    "סתריה": "Sitriya",
    "ע'ג'ר": "Ghajar",
    "עבדון": "Avdon",
    "עברון": "Evron",
    "עגור": "Agur",
    "עדי": "Adi",
    "עדנים": "Adanim",
    "עוזה": "Uza",
    "עוזייר": "Uzeir",
    "עולש": "Ulash",
    "עומר": "Omer",
    "עופר": "Ofer",
    "עופרה": "Ofra",
    "עוצם": "Otzem",
    "עוקבי (בנו עוקבה)": "Uqbi (Bnei Uqba)",
    "עזר": "Ezer",
    "עזריאל": "Azriel",
    "עזריה": "Azarya",
    "עזריקם": "Azrikam",
    "עטאוונה (שבט)": "Atawna (tribe)",
    "עטרת": "Ateret",
    "עידן": "Idan",
    "עיילבון": "Eilabun",
    "עיינות": "Ayyanot",
    "עילוט": "I'lot",
    "עין איילה": "Ein Ayala",
    "עין אל-אסד": "Ein al-Asad",
    "עין גב": "Ein Gev",
    "עין גדי": "Ein Gedi",
    "עין דור": "Ein Dor",
    "עין הבשור": "Ein HaBesor",
    "עין הוד": "Ein Hod",
    "עין החורש": "Ein HaHoresh",
    "עין המפרץ": "Ein HaMifratz",
    "עין הנצי\"ב": "Ein HaNatziv",
    "עין העמק": "Ein HaEmek",
    "עין השופט": "Ein HaShofet",
    "עין השלושה": "Ein HaShlosha",
    "עין ורד": "Ein Vered",
    "עין זיוון": "Ein Zivan",
    "עין חוד": "Ein Hud",
    "עין חרוד (איחוד)": "Ein Harod (Ichud)",
    "עין חרוד (מאוחד)": "Ein Harod (Meuchad)",
    "עין יהב": "Ein Yahav",
    "עין יעקב": "Ein Ya'akov",
    "עין כרמל": "Ein Carmel",
    "עין מאהל": "Ein Mahil",
    "עין נקובא": "Ein Naqquba",
    "עין עירון": "Ein Iron",
    "עין צורים": "Ein Tzurim",
    "עין קנייא": "Ein Qiniyye",
    "עין ראפה": "Ein Rafa",
    "עין שמר": "Ein Shemer",
    "עין שריד": "Ein Sarid",
    "עין תמר": "Ein Tamar",
    "עינת": "Einat",
    "עכו": "Acre",
    "עלומים": "Alumim",
    "עלי": "Eli",
    "עלי זהב": "Eli Zahav",
    "עלמה": "Alma",
    "עלמון": "Almon",
    "עמוקה": "Amuka",
    "עמיחי": "Amichai",
    "עמינדב": "Aminadav",
    "עמיעד": "Ami'ad",
    "עמיעוז": "Ami'oz",
    "עמיקם": "Amikam",
    "עמיר": "Amir",
    "עמנואל": "Immanuel",
    "עמקה": "Amka",
    "ענב": "Enaf",
    "עספיא": "Isfiya",
    "עפולה": "Afula",
    "עץ אפרים": "Etz Ephraim",
    "עצמון שגב": "Atzmon Segev",
    "עראבה": "Arraba",
    "עראמשה": "Ar'ara",
    "ערב אל נעים": "Arab al-Na'im",
    "ערד": "Arad",
    "ערוגות": "Arugot",
    "ערערה": "Ar'ara",
    "ערערה-בנגב": "Ar'ara-BaNegev",
    "עשרת": "Aseret",
    "עתלית": "Atlit",
    "עתניאל": "Otniel",
    "פארן": "Paran",
    "פדואל": "Peduel",
    "פדויים": "Pduyim",
    "פדיה": "Pdaya",
    "פוריה - כפר עבודה": "Poriya - Kfar Avoda",
    "פוריה - נווה עובד": "Poriya - Neve Oved",
    "פוריה עילית": "Poriya Illit",
    "פוריידיס": "Fureidis",
    "פורת": "Porat",
    "פטיש": "Patish",
    "פלמחים": "Palmachim",
    "פני חבר": "Pnei Hever",
    "פסגות": "Psagot",
    "פסוטה": "Fassuta",
    "פעמי תש\"ז": "Pa'amei Tashaz",
    "פצאל": "Petza'el",
    "פקיעין (בוקייעה)": "Peki'in (Buqei'a)",
    "פקיעין חדשה": "Peki'in Hadasha",
    "פרדס חנה-כרכור": "Pardes Hanna-Karkur",
    "פרדסיה": "Pardesiya",
    "פרוד": "Parod",
    "פרזון": "Prazon",
    "פרי גן": "Pri Gan",
    "פתח תקווה": "Petah Tikva",
    "פתחיה": "Ptachia",
    "צאלים": "Ze'elim",
    "צביה": "Tzvia",
    "צבעון": "Tziv'on",
    "צובה": "Tzova",
    "צוחר": "Tzohar",
    "צופים": "Tzofim",
    "צופית": "Tzofit",
    "צופר": "Tzofar",
    "צוקי ים": "Tzukei Yam",
    "צוקים": "Tzukim",
    "צור הדסה": "Tzur Hadassa",
    "צור יצחק": "Tzur Yitzhak",
    "צור משה": "Tzur Moshe",
    "צור נתן": "Tzur Natan",
    "צוריאל": "Tzuriel",
    "צורית": "Tzurit",
    "ציפורי": "Tzippori",
    "צלפון": "Tzalfon",
    "צנדלה": "Tzandala",
    "צפריה": "Tzafriya",
    "צפרירים": "Tzafririm",
    "צפת": "Safed",
    "צרופה": "Tzrufa",
    "צרעה": "Tzora",
    "קבועה (שבט)": "Qabua (tribe)",
    "קבוצת יבנה": "Kvutzat Yavne",
    "קדומים": "Kedumim",
    "קדימה-צורן": "Kadima-Tzoran",
    "קדמת צבי": "Kidmat Tzvi",
    "קדר": "Kedar",
    "קדרון": "Kidron",
    "קדרים": "Kadarim",
    "קודייראת א-צאנע(שבט)": "Qudeirat al-Sani' (tribe)",
    "קוואעין (שבט)": "Qua'in (tribe)",
    "קוממיות": "Komemiyut",
    "קורנית": "Kornit",
    "קטורה": "Ketura",
    "קיסריה": "Caesarea",
    "קלחים": "Klachim",
    "קליה": "Kalia",
    "קלנסווה": "Qalansawe",
    "קלע": "Kela",
    "קציר": "Katzir",
    "קצר א-סר": "Qasr al-Sir",
    "קצרין": "Katzrin",
    "קרית אונו": "Kiryat Ono",
    "קרית ארבע": "Kiryat Arba",
    "קרית אתא": "Kiryat Ata",
    "קרית ביאליק": "Kiryat Bialik",
    "קרית גת": "Kiryat Gat",
    "קרית טבעון": "Kiryat Tiv'on",
    "קרית ים": "Kiryat Yam",
    "קרית יערים": "Kiryat Ye'arim",
    "קרית מוצקין": "Kiryat Motzkin",
    "קרית מלאכי": "Kiryat Malakhi",
    "קרית נטפים": "Kiryat Netafim",
    "קרית ענבים": "Kiryat Anavim",
    "קרית עקרון": "Kiryat Ekron",
    "קרית שמונה": "Kiryat Shmona",
    "קרני שומרון": "Karni Shomron",
    "קשת": "Keshet",
    "ראמה": "Rama",
    "ראס אל-עין": "Ras al-Ein",
    "ראס עלי": "Ras Ali",
    "ראש העין": "Rosh HaAyin",
    "ראש פינה": "Rosh Pina",
    "ראש צורים": "Rosh Tzurim",
    "ראשון לציון": "Rishon LeZion",
    "רבבה": "Revava",
    "רבדים": "Revadim",
    "רביבים": "Revivim",
    "רגבה": "Regba",
    "רגבים": "Regavim",
    "רהט": "Rahat",
    "רווחה": "Revaha",
    "רוויה": "Revaya",
    "רוחמה": "Ruhama",
    "רומאנה": "Rumana",
    "רומת הייב": "Rumat Heib",
    "רועי": "Roei",
    "רחוב": "Rehov",
    "רחובות": "Rehovot",
    "רחלים": "Rechelim",
    "ריחאניה": "Rehaniya",
    "ריחן": "Rihan",
    "ריינה": "Reineh",
    "רימונים": "Rimonim",
    "רינתיה": "Rinatya",
    "רכסים": "Rechasim",
    "רם-און": "Ram-On",
    "רמות": "Ramot",
    "רמות השבים": "Ramot HaShavim",
    "רמות מאיר": "Ramot Meir",
    "רמות מנשה": "Ramot Menashe",
    "רמות נפתלי": "Ramot Naftali",
    "רמלה": "Ramla",
    "רמת גן": "Ramat Gan",
    "רמת דוד": "Ramat David",
    "רמת הכובש": "Ramat HaKovesh",
    "רמת השופט": "Ramat HaShofet",
    "רמת השרון": "Ramat HaSharon",
    "רמת יוחנן": "Ramat Yohanan",
    "רמת ישי": "Ramat Yishai",
    "רמת מגשימים": "Ramat Magshimim",
    "רמת צבי": "Ramat Tzvi",
    "רמת רזיאל": "Ramat Raziel",
    "רמת רחל": "Ramat Rachel",
    "רנן": "Renan",
    "רעים": "Re'im",
    "רעננה": "Ra'anana",
    "רקפת": "Rakefet",
    "רשפון": "Rishpon",
    "רשפים": "Reshef",
    "רתמים": "Retamim",
    "שאר ישוב": "She'ar Yashuv",
    "שבי ציון": "Shavei Zion",
    "שבי שומרון": "Shavei Shomron",
    "שבלי - אום אל-גנם": "Shibli–Umm al-Ghanam",
    "שגב-שלום": "Segev-Shalom",
    "שדה אילן": "Sde Ilan",
    "שדה אליהו": "Sde Eliyahu",
    "שדה אליעזר": "Sde Eliezer",
    "שדה בוקר": "Sde Boker",
    "שדה דוד": "Sde David",
    "שדה ורבורג": "Sde Warburg",
    "שדה יואב": "Sde Yo'av",
    "שדה יעקב": "Sde Ya'akov",
    "שדה יצחק": "Sde Yitzhak",
    "שדה משה": "Sde Moshe",
    "שדה נחום": "Sde Nahum",
    "שדה נחמיה": "Sde Nehemia",
    "שדה ניצן": "Sde Nitzan",
    "שדה עוזיהו": "Sde Uziyahu",
    "שדה צבי": "Sde Tzvi",
    "שדות ים": "Sdot Yam",
    "שדות מיכה": "Sdot Mikha",
    "שדי אברהם": "Sdei Avraham",
    "שדי חמד": "Sdei Hemed",
    "שדי תרומות": "Sdei Terumot",
    "שדמה": "Shdema",
    "שדמות דבורה": "Shadmot Devora",
    "שדמות מחולה": "Shadmot Mehola",
    "שדרות": "Sderot",
    "שואבה": "Sho'eva",
    "שובה": "Shuva",
    "שובל": "Shoval",
    "שוהם": "Shoham",
    "שומרה": "Shomera",
    "שומריה": "Shomriya",
    "שוקדה": "Shokeda",
    "שורש": "Shoresh",
    "שורשים": "Shorashim",
    "שושנת העמקים": "Shoshannat HaAmakim",
    "שזור": "Shezor",
    "שחר": "Shachar",
    "שחרות": "Shacharut",
    "שיבולים": "Shibolim",
    "שייח' דנון": "Sheikh Danun",
    "שילה": "Shiloh",
    "שילת": "Shilat",
    "שכניה": "Shekhanya",
    "שלווה": "Shalva",
    "שלוחות": "Shluhot",
    "שלומי": "Shlomi",
    "שלומית": "Shlomit",
    "שמיר": "Shamir",
    "שמעה": "Shim'a",
    "שמרת": "Shamrat",
    "שמשית": "Shimshit",
    "שני": "Shani",
    "שניר": "Snir",
    "שעב": "Sha'ab",
    "שעל": "Sha'al",
    "שעלבים": "Sha'alvim",
    "שער אפרים": "Sha'ar Ephraim",
    "שער הגולן": "Sha'ar HaGolan",
    "שער העמקים": "Sha'ar HaAmakim",
    "שער מנשה": "Sha'ar Menashe",
    "שערי תקווה": "Sha'arei Tikva",
    "שפיים": "Shefayim",
    "שפיר": "Shafir",
    "שפר": "Shefer",
    "שפרעם": "Shefar'am",
    "שקד": "Shaked",
    "שקף": "Shekef",
    "שרונה": "Sharona",
    "שריגים (לי-און)": "Sarigim (Li-On)",
    "שריד": "Sarid",
    "שרשרת": "Sharsheret",
    "שתולה": "Shtula",
    "שתולים": "Shtulim",
    "תאשור": "Ta'ashur",
    "תדהר": "Tidhar",
    "תובל": "Tuval",
    "תומר": "Tomer",
    "תושיה": "Tushiya",
    "תימורים": "Timorim",
    "תירוש": "Tirosh",
    "תל אביב - יפו": "Tel Aviv - Jaffa",
    "תל יוסף": "Tel Yosef",
    "תל יצחק": "Tel Yitzhak",
    "תל מונד": "Tel Mond",
    "תל עדשים": "Tel Adashim",
    "תל קציר": "Tel Katzir",
    "תל שבע": "Tel Sheva",
    "תל תאומים": "Tel Te'omim",
    "תלם": "Telem",
    "תלמי אליהו": "Talmei Eliyahu",
    "תלמי אלעזר": "Talmei Elazar",
    "תלמי ביל\"ו": "Talmei Bilu",
    "תלמי יוסף": "Talmei Yosef",
    "תלמי יחיאל": "Talmei Yehiel",
    "תלמי יפה": "Talmei Yafe",
    "תלמים": "Talmey",
    "תמרת": "Timrat",
    "תנובות": "Tenu'ot",
    "תעוז": "Ta'oz",
    "תפרח": "Tifrach",
    "תקומה": "Tkuma",
    "תקוע": "Tekoa",
    "תראבין א-צאנע (שבט)": "Tarabin al-Sani' (tribe)",
    "תראבין א-צאנע(ישוב)": "Tarabin al-Sani' (locality)",
    "תרום": "Tarom"
}

winning_parties_translation = {
    'מחל': party.likud.name,
    'ל': party.yisrael_beiteinu.name,
    'פה': party.blue_and_white.name,
    'ודעם': party.joint_list.name,
    'שס': party.shas.name,
    'ג': party.united_torah_judaism.name,
    'טב': party.yamina.name,
    'אמת': party.labour.name,
    'מרצ': party.democratic_union.name,
    'כ': party.kulanu.name,
}

losing_parties_list = [
    'ז', 'זכ', 'זן', 'זץ', 'י', 'יז', 'ינ', 'יף', 'יק', 'כי', 'כף', 'נ', 'נך', 'נץ', 'ףז', 'צ', 'צן', 'ץ', 'ק', 'קך', 'קץ', 'רק',
]

columns_translation = {
    'סמל ישוב': 'settlement_code',
    'קלפי': 'booth_number',
    'שם ישוב': 'settlement_name',
    'ריכוז': 'concentration',
    'מצביעים': 'voters',
    'פסולים': 'invalid_votes',
    'כשרים': 'valid_votes',
    'stat2011': 'stat2011',
    'yishuv_stat2011': 'yishuv_stat2011',
    'socio_econ_cluster_2015': 'socio_econ_cluster_2015',
    'is_stable': 'is_stable',
}

ignored_columns_list = [
    'סמל ועדה',
    'ברזל',
    'שופט',
    'בזב',
]

